services:
    trmnl-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4567:8080"
        environment:
            #- APP_KEY=
            - PHP_OPCACHE_ENABLE=1
            - TRMNL_PROXY_REFRESH_MINUTES=15
            - DB_DATABASE=trmnl
            - APP_TIMEZONE=${APP_TIMEZONE:-Australia/Sydney}
            - DB_CONNECTION=${DB_CONNECTION:-mariadb}
            - DB_HOST=${DB_HOST:-mariadb}
            - DB_PORT=${DB_PORT:-3306}
            - DB_USERNAME=${DB_USERNAME:-root}
            - DB_PASSWORD=${DB_PASSWORD:-root}
            - APP_URL=${APP_URL:-http://localhost:4567}
            - APP_ENV=${APP_ENV:-local}
            - APP_DEBUG=${APP_DEBUG:-true}
            - APP_NAME=${APP_NAME:-Trmnl}
            - APP_LOCALE=${APP_LOCALE:-en}
            # Users.au OAuth Configuration
            - USERSAU_CLIENT_ID=${USERSAU_CLIENT_ID:-}
            - USERSAU_CLIENT_SECRET=${USERSAU_CLIENT_SECRET:-}
            - USERSAU_REDIRECT_URI=${USERSAU_REDIRECT_URI:-${APP_URL}/auth/usersau/callback}
            - USERSAU_HOST=${USERSAU_HOST:-}
        volumes:
           - database:/var/www/html/database/storage
           - storage:/var/www/html/storage/app/public/images/generated
        restart: unless-stopped
        networks:
            - caddy
        #platform: "linux/arm64/v8"

networks:
    caddy:
        external: true

volumes:
    database:
    storage:

